# Generated by Django 2.2 on 2022-11-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eazy_lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
    ]
